[project]
name = "node_link"
version = "0.1.0"
readme = "README.md"
dependencies = ["rerun-sdk"]

[project.scripts]
node_link = "node_link:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
