[package]
name = "node_link"
version = "0.20.0-alpha.1+dev"
edition = "2021"
rust-version = "1.79"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/top/rerun", features = ["clap"] }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }

# Iterate over enums
strum = "0.26"
strum_macros = "0.26"
itertools = "0.13"
