[project]
name = "node-link"
version = "0.1.0"
# requires-python = "<3.12"
dependencies = ["rerun-sdk"]

[project.scripts]
node_link_graphs = "node_link_graphs:main"

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
